Portfolio Mobile Version: Created toolbar and headline
Khawanin/Portfolio pull request #1
Opened 2022-04-22 21:28 UTC by Khawanin

#Portfolio Mobile version
##In this project:

**Used flexbox for aligning items**
**Created toolbar and headline of the project**
**Used linters for validation and beautifying the code**

2022-04-22 22:41 UTC, bimbolabuari requested changes
Hi @Khawanin,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
-  Use flexbox to layout element
- Correct Github flow
- Use of background images as required.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 22:41 UTC, bimbolabuari commented on index.html
> +  </nav>
For semantic HTML best pratices,  Kindly give this section an `header` tag instead of the `nav` tag

2022-04-22 22:41 UTC, bimbolabuari commented on index.html
> +  </nav>
For semantic HTML best pratices,  Kindly give this section an `header` tag instead of the `nav` tag

2022-04-22 22:41 UTC, bimbolabuari commented on index.html
> +      <div id="nav-icon"><img src="./Images/Union.png" alt="header icon"></div>
Kindly rename this `div` tag to `nav` tag as the purpose of the icon is to display a the nav links. 👍

2022-04-22 22:41 UTC, bimbolabuari commented on index.html
> +    </div>
Let's use an unordered list ( `ul` tag) to list out the icons and `li` tag per icon 🙂

2022-04-22 22:41 UTC, bimbolabuari commented on style.css
> +#nav-icon {
For CSS best pratice, Kindly use classes in order to style element instead of id

2022-04-22 22:41 UTC, bimbolabuari commented on style.css
> +  line-height: 150px;
Kindly fix the line height to like 75px in order to reduce the spacing. 👍 
![image](https://user-images.githubusercontent.com/66112760/164813302-3949515f-5c6f-481b-a3a7-aba12eae2bd0.png)

2022-04-23 01:44 UTC, smunozmo approved these changes
Hi @Khawanin, 👋 

## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 💯  💯  💯 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>


Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 01:44 UTC, smunozmo commented on style.css
> +}
[OPTIONAL] Your portfolio is looking great, well done! You could reduce a little bit more the `line-height` and it would look just like the Figma template.

2022-04-23 10:07 UTC, merged