Portfolio: Desktop version
Khawanin/Portfolio pull request #6
Opened 2022-08-26 23:57 UTC by Khawanin

## Portfolio: Responsive layout
The previous version was built specifically for mobile devices.
In This project we:
- used media queries to make it responsive
- used both flexbox and grid to align the elements
- used linters to beautify our source code

2022-08-27 02:15 UTC, emmiiorji requested changes
Hi @Khawanin, 
# Status: Changes Required ♻️

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Almost there](https://user-images.githubusercontent.com/20554583/187007730-89db6038-cc0d-4c5d-a1c0-961759061c75.gif)


## Good Highlights ✅

- Descriptive PR
- Linter checks are passing
- Adherence to GitHub flow
- Good commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

You can also consider the following:
- I recommend that you include the MIT license file in the root folder of your project so that the link given in the License section of your README file wouldn't be a broken one.
![image](https://user-images.githubusercontent.com/20554583/187007798-80ddd3bb-100d-499a-8a0d-09e644c103d9.png)
You can customize [this](https://github.com/microverseinc/readme-template/blob/master/MIT.md). You can also set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

- I suggest that you ignore the .vscode directory since it's only a local setting of your code editor. You can achieve this by first deleting the folder(after copying it elsewhere), committing and pushing to GitHub. You may now restore the folder and add it to .gitignore.

_Every optional comment is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 02:15 UTC, emmiiorji commented on index.html
> +          </ul>
Please, could we make the nav bar fixed as suggested by the Figma design? Sticking to the design as much as possible (e.g. font, colors, images, text, margins) will be a good habit right now. You'll get more prepared for a typical workplace experience where you might be required to reproduce a given design as strictly as possible.

So, let's follow the original vision if it's pretty and works, it will be a wonderful website.

Your design:
![image](https://user-images.githubusercontent.com/20554583/187008178-76afaca6-ac71-4ca9-9b63-a404e1708b5d.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/187008152-72ecc189-177d-4e2a-a4f6-e9bd49775f7b.png)

2022-08-27 02:15 UTC, emmiiorji commented on index.html
>            <p class="self-intro">I’m a software developer! I can help you build a product , feature or website Look
Kindly ensure that the intro section covers at least the height of the view port. This looks better and is what the design gives us. Check the above comment for more reasons we should stick to the design when given.

Your design:
![image](https://user-images.githubusercontent.com/20554583/187008468-e1b3a3b7-87ed-46ea-8efc-6c85b7665118.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/187008686-39f3babf-ef3c-4cd1-9702-696f2e9811dc.png)

2022-08-27 02:15 UTC, emmiiorji commented on index.html
>            <p class="self-intro">I’m a software developer! I can help you build a product , feature or website Look
Also, kindly ensure that the heading, intro paragraph and the social icons align as is on the design.

2022-08-27 02:15 UTC, emmiiorji commented on index.html
> +            </ul>
Your project cards look great. However, a closer look shows that the project images and the descriptions alternate positions in the next project. Kindly adjust the design to implement it too.

Your design:
![image](https://user-images.githubusercontent.com/20554583/187008922-cf302451-97d5-4190-8837-9b26779b0a33.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/187008933-7d8b4de9-358f-41f8-99c8-0aba73f5cfa5.png)

2022-08-27 02:15 UTC, emmiiorji commented on index.html
> +            </ul>
Also, kindly centralize the projects as illustrated. There seems to be a higher margin on the right than on the left. Centralizing it looks better and follows the design.

2022-08-27 02:15 UTC, emmiiorji commented on index.html
>            <ul class="list-1">
Please, make the project images occupy the space much more fully and share the horizontal space equally with the project description. This is how the design gives it. Check the comment above for more reason you should stick to the design.

Your implementation:
![image](https://user-images.githubusercontent.com/20554583/187009293-a711041d-a294-4930-85c8-b4ceee00bb63.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/187009307-48b591b4-d63c-41e4-8473-ef1f65e1846b.png)


The margin shown below seems to be having an effect on the alignments:
![image](https://user-images.githubusercontent.com/20554583/187009683-29ded926-3df7-4347-804d-e200cc484539.png)

2022-08-27 02:15 UTC, emmiiorji commented on index.html
> +        <div class="project-btn"><button class="pro-btn">See Project</button></div>
Kindly implement the button interactions to match the design much more closely. This will give users a better experience on the website.

Your _button enabled_ interaction:
![image](https://user-images.githubusercontent.com/20554583/187009414-996a89ff-32bd-4648-853d-3b37dc8c41c3.png)

Figma button interactions:
![image](https://user-images.githubusercontent.com/20554583/187009431-f05a69f2-31f7-4802-9905-ae82131e050e.png)

2022-08-27 02:15 UTC, emmiiorji commented on index.html
> -      <h2 class="multi-post">Multi-Post stories</h2>
Kindly modify the _about me_ section to match the design on Figma. Check the comment above for more reasons you should stick to a given design.

Your design:
![image](https://user-images.githubusercontent.com/20554583/187010136-e77d3f22-4845-48d0-8487-81a401dc8107.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/187010120-e29265f5-53eb-4979-96e3-b303495701fe.png)

2022-08-27 02:15 UTC, emmiiorji commented on index.html
> +        <textarea class="message" name="message" maxlength="500" placeholder="Write your message here"
Please, also modify the contact me section to match the design on figma. Check the comment above for more reason you should stick to your given design.

Your design:
![image](https://user-images.githubusercontent.com/20554583/187010263-a9b809fb-730c-4177-8725-faa01d90b1be.png)


Figma design:
![image](https://user-images.githubusercontent.com/20554583/187010295-54ce6008-e5bd-4ac2-99bd-430e8c2152d2.png)

2022-09-02 12:00 UTC, awais-amjed requested changes
# STATUS: CHANGES REQUIRED ♻️

Hi @Khawanin , 

Good job so far! 👏👏
There are some issues that you still need to work on to go to the next project but you are almost there! 🤗🥳🙌

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 12:00 UTC, awais-amjed commented on index.html
>            <ul class="social-icons">
[OPTIONAL] Your headline section looks awesome 👏👏 but Kindly add some space between `LET'S CONNECT` and social icons to make it look even better

Your design:

![image](https://user-images.githubusercontent.com/73714615/188134386-33fb7d5d-1cba-4ebf-8dd4-aa28a24ca8c9.png)

Figma design:

![image](https://user-images.githubusercontent.com/73714615/188134475-eb00ba3c-919f-48f7-8737-4b6bf4d527ad.png)

2022-09-02 12:00 UTC, awais-amjed commented on index.html
> +      </div>
Kindly note that your projects on the mobile view don't look the same as the Figma design, Kindly fix them 🤗

Your design:

![image](https://user-images.githubusercontent.com/73714615/188137367-e4ecdec5-8de9-4c86-9390-6ceaf4aced72.png)

Figma design:

![image](https://user-images.githubusercontent.com/73714615/188137104-46208f2f-0cfa-4f54-9162-85754d22bfb1.png)

2022-09-02 12:00 UTC, awais-amjed commented on index.html
> +          or a project that needs coding. I’d love to help with it.</p>
Kindly fix the color of this paragraph in mobile view 🤗

Your design:

![image](https://user-images.githubusercontent.com/73714615/188138114-6d3af4ec-5c99-4854-b73e-c2fec7d1b496.png)

Figma design;

![image](https://user-images.githubusercontent.com/73714615/188138053-4f9100b0-5428-4918-938a-549d45306724.png)

2022-09-02 12:00 UTC, awais-amjed commented on index.html
> +      <div><button class="resume" type="submit">Get my resume</button></div>
Please also update the style of this button to match the other buttons in your webpage 🤗

Yoru design:

![image](https://user-images.githubusercontent.com/73714615/188138414-727bcf1e-2437-471c-b60a-b6c72a696b90.png)

Figma design:

![image](https://user-images.githubusercontent.com/73714615/188138457-731854d9-c204-4f11-8c69-7af892a20c7c.png)

2022-09-02 12:03 UTC, awais-amjed commented
@Khawanin Kindly also note that your branch has conflict issues, I forgot to mention it in my review.
Kindly fix the conflict issues and your GitHub actions should start working too 🤗

_PS: I checked the Linters on my machine and they are passing so kudos on that_ 👏👏

2022-09-02 16:31 UTC, Nemwel-Boniface approved these changes
## Hello @Khawanin               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the requested changes good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 16:31 UTC, Nemwel-Boniface commented on index.html
> +                required></textarea>
- [ ] [OPTIONAL] It appears that the new changes introduced broke the design a little bit. Kindly make the width of the text area to match the chosen Figma design.

**This is how I am seeing it right now:**

![image](https://user-images.githubusercontent.com/86318284/188196756-cf0f3fcb-0871-47c4-97a3-3dad28265d82.png)

2022-09-02 16:35 UTC, merged